version: "4"
services:
  springboot-app:
    image: hr-recrutement
    restart: always
    build: .
    ports:
      - 8085:8085
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306


  mysqldb:
    container_name: mysqldata
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: LabSoft_recruitement
      MYSQL_ROOT_PASSWORD: root
